{{- if .Values.canaryAlert }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-canary-deploy
spec:
  groups:
    - name: deployd
      rules:
        - alert: NAIS deploy canary does not sing
          expr: |
            min(nais_testapp_time_since_deploy{app="nais-deploy-canary",namespace="nais-verification"}) > 900
          for: 5m
          labels:
            namespace: nais-system
            severity: danger
          annotations:
            summary: |
              Problem with NAIS deploy

              Canary application should deploy every 5 minutes, but has not been deployed successfully in over 20 minutes.
            consequence: NAIS deploy is probably unavailable. Some or all users might not be able to deploy
            action: |
              * `kubectl --context management -n nais-system describe job -l app=canary-deployer`
              * `kubectl --context management -n nais-system describe deploy hookd`
              * Ensure deployd is running in cluster that alerts
              * Ensure that hookd and deployd can talk to each other using gRPC
              * Check *hookd*, *deployd* and *naiserator* error logs

              Documentation: https://github.com/nais/deploy
              Logs: https://logs.adeo.no/goto/cb6b89c655dcb051fa633ce35070d385
              Instrumentation: https://monitoring.nais.io/d/9Wb381o4k/deploy-canary
              2nd line: @nais-features
        - alert: NAIS deploy canary metric missing
          expr: |
            absent(nais_testapp_time_since_deploy{app="nais-deploy-canary",namespace="nais-verification"})
          for: 5m
          labels:
            namespace: nais-system
            severity: danger
          annotations:
            summary: |
              The metric used to determine if the canary application is deployed is missing.

              Canary application should produce metrics in order for other alerts to work.
            consequence: NAIS deploy might be available, but we can't know.
            action: |
              * `kubectl --context management -n nais-system describe job -l app=canary-deployer`
              * `kubectl --context management -n nais-system describe deploy hookd`
              * Ensure deployd is running in cluster that alerts

              Documentation: https://github.com/nais/deploy
              Logs: https://logs.adeo.no/goto/cb6b89c655dcb051fa633ce35070d385
              Instrumentation: https://monitoring.nais.io/d/9Wb381o4k/deploy-canary
{{- end }}
