{{- if eq .Values.cluster "prod-fss" }}
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: deployment-event-relays
  labels:
    team: nais
    {{- include "deployd.labels" . | nindent 4 }}
spec:
  image: {{ .Values.deploymentEventRelays.image.repository }}:{{ .Values.deploymentEventRelays.image.tag }}
  port: 8080
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
  envFrom:
    - secret: deployment-event-relays
  webproxy: false
  skipCaBundle: false
  kafka:
    pool: {{ .Values.deploymentEventRelays.kafka.pool }}
{{- end }}
