apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployd.fullname" . }}-env
  labels:
    {{- include "deployd.labels" . | nindent 4 }}
type: kubernetes.io/Opaque
stringData:
  DEPLOYD_CLUSTER: "{{ .Values.cluster }}"
  DEPLOYD_GRPC_SERVER: "{{ .Values.hookdHost }}:443"
  DEPLOYD_GRPC_AUTHENTICATION: "true"
  DEPLOYD_GRPC_USE_TLS: "true"
  DEPLOYD_HOOKD_KEY: "{{ .Values.preSharedKey }}"
  DEPLOYD_LOG_FORMAT: json
  DEPLOYD_LOG_LEVEL: trace
  DEPLOYD_METRICS_LISTEN_ADDRESS: "0.0.0.0:8080"
  DEPLOYD_METRICS_PATH: "/metrics"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.otelExporterOtlpEndpoint }}"
---
{{- if eq .Values.cluster "prod-fss" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: deployment-event-relays
  labels:
    {{- include "deployd.labels" . | nindent 4 }}
stringData:
  DER_LOG_FORMAT: "json"
  DER_METRICS_BIND_ADDRESS: "0.0.0.0:8080"
  DER_INFLUXDB_USERNAME: "{{ .Values.deploymentEventRelays.influxdb.user }}"
  DER_INFLUXDB_PASSWORD: "{{ .Values.deploymentEventRelays.influxdb.password }}"
  DER_INFLUXDB_URL: "{{ .Values.deploymentEventRelays.influxdb.url }}"
  DER_NORA_URL: "{{ .Values.deploymentEventRelays.nora.url }}"
  DER_VERA_URL: "{{ .Values.deploymentEventRelays.vera.url }}"
  DER_NULL_ENABLED: "{{ .Values.deploymentEventRelays.nullEnabled }}"
  DER_KAFKA_TOPIC: "{{ .Values.deploymentEventRelays.kafka.topic }}"
  DER_KAFKA_GROUP_ID_PREFIX: "{{ .Values.deploymentEventRelays.kafka.groupIdPrefix }}"
{{- end }}
