kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "deployd.fullname" . }}
  labels:
    {{- include "deployd.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "deployd.labels" . | nindent 4 }}
  name: {{ include "deployd.fullname" . }}
rules:
  - apiGroups:
    - "*"
    resources:
    - "serviceaccounts"
    - "secrets"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - "*"
    resources:
    - "serviceaccounts"
    verbs:
    - impersonate
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "deployd.labels" . | nindent 4 }}
  name: {{ include "deployd.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "deployd.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "deployd.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
