version: "3"
services:
  kafka:
    image: "spotify/kafka"
    ports:
      - "9092:9092"
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
  postgres:
    image: postgres:11-alpine
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=root"
