name: "NAIS Docker Push"
description: "Build and push docker image to the NAIS registry"
inputs:
  config:
    description: "Configuration. See readme for details"
    required: true
  push_image:
    description: "Push image to registry"
    required: true
    default: "true"
  dockerfile:
    description: "Dockerfile"
    required: true
    default: "Dockerfile"
  docker_context:
    description: "Docker context"
    required: true
    default: "."
outputs:
  tag:
    description: "Release tag"
    value: ${{ steps.setup.outputs.NEW_VERSION }}
  image:
    description: "Image name"
    value: ${{ steps.setup.outputs.registry }}/${{ steps.setup.outputs.REPO_NAME }}:${{ steps.setup.outputs.NEW_VERSION }}
runs:
  using: "composite"
  steps:
    - name: Setup environment
      shell: bash
      id: "setup"
      run: |
        echo '${{ inputs.config }}' | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_OUTPUT
        echo "NEW_VERSION=$(date '+%Y.%-m.%-d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "REPO_NAME=${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER\//}" >> $GITHUB_OUTPUT
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1.0.0"
      with:
        workload_identity_provider: ${{ steps.setup.outputs.workload_identity_provider }}
        service_account: ${{ steps.setup.outputs.google_service_account }}
        token_format: "access_token"
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ steps.setup.outputs.registry }}
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"
    - name: Build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push_image }}
        tags: ${{ steps.setup.outputs.registry }}/${{ steps.setup.outputs.REPO_NAME }}:${{ steps.setup.outputs.NEW_VERSION }}
        labels: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ steps.setup.outputs.NEW_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
