# canary release
#
# this is an application which reports how long it took to deploy.

---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/skipDeploymentMessage: "true"
  labels:
    team: aura
  name: nais-deploy-canary
  namespace: aura
spec:
  env:
  - name: DEPLOY_START
    value: "{{ now }}"
  image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7
  liveness:
    path: /ping
  port: 8080
  readiness:
    path: /ping
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /metrics
