# Default values for deployd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/deployd
  pullPolicy: IfNotPresent
  tag: main

imagePullSecrets: []

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1069
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 1024Mi

cluster: # mapped by fasit
preSharedKey: # mapped by fasit
hookdHost: # mapped by fasit

caBundle: false
extraEnv: {}

deploymentEventRelays:
  image:
    repository: "ghcr.io/nais/deployment-event-relays"
    tag: "2021-05-26-726d879"
  influxdb:
    url: "http://influxdb.adeo.no:8086/write?db=metrics"
    user: "nais"
    password: ""
  nora:
    url: ""
  vera:
    url: "https://vera.intern.nav.no/api/v1/deploylog"
  nullEnabled: false
  kafka:
    groupIdPrefix: "deployment-event-relays"
    pool: "nav-infrastructure"
    topic: "aura.dev-rapid"

canaryAlert: true

otelExporterOtlpEndpoint: # mapped by fasit
