name: "Upload to CDN"
description: "Upload static assets to CDN"
inputs:
  team:
    description: "Team slug"
    required: true
  tenant:
    description: "Tenant slug"
    default: "nav"
    required: true
  source:
    description: "Source directory"
    required: true
  destination:
    description: "Destination directory"
    required: true
  source_keep_parent_name:
    description: "Keep parent directory name when uploading"
    required: false
    default: "true"
  cache_invalidation:
    description: "Cache invalidation"
    required: false
    default: "false"
  no_cache_paths:
    description: "Comma separated list of paths that should not be cached"
    required: false
    default: ""
  project_id:
    description: "Google Cloud project ID where buckets are hosted"
    required: true
  identity_provider:
    description: "Google Workload Identity Provider"
    required: true

outputs:
  uploaded:
    description: "Uploaded files"
    value: ${{ steps.legacy.outputs.uploaded }}

runs:
  using: "composite"
  steps:
    - id: legacy
      uses: "navikt/frontend/actions/cdn-upload/v1@main"
      with:
        cdn-team-name: ${{ inputs.team }}
        source: ${{ inputs.source }}
        destination: ${{ inputs.destination }}
        source-keep-parent-name: ${{ inputs.source_keep_parent_name }}
        cache-invalidation: ${{ inputs.cache_invalidation }}
        no-cache-paths: ${{ inputs.no_cache_paths }}
