apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hookd.name" . }}
  labels:
    {{- include "hookd.labels" . | nindent 4 }}
spec:
  egress:
  # All 34.88.0.0/16 IP addresses in this list
  # point to Postgres databases in management projects.
  # FIXME: provision elsewhere?
  # FIXME: Fasit integration?
  - to:
    - ipBlock:
        cidr: 34.88.176.78/32
    - ipBlock:
        cidr: 34.88.4.118/32
    - ipBlock:
        cidr: 34.88.161.247/32
    - ipBlock:
        cidr: 35.228.252.151/32
    - ipBlock:
        cidr: 34.88.111.83/32
    - ipBlock:
        cidr: 34.88.6.186/32
    - ipBlock:
        cidr: 35.228.159.4/32
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nais-system
      podSelector:
        matchLabels:
          app: nais-api
  podSelector:
    matchLabels:
      {{- include "hookd.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
