apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hookd.name" . }}
  labels:
    {{- include "hookd.labels" . | nindent 4 }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: "{{ .Values.database.ip }}/32"
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nais-system
      podSelector:
        matchLabels:
          app: nais-api
  podSelector:
    matchLabels:
      {{- include "hookd.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
