apiVersion: v1
kind: Service
metadata:
  name: {{ include "hookd.name" . }}
  labels:
    {{- include "hookd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector: 
    {{- include "hookd.selectorLabels" . | nindent 4 }}
