apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: aura
  name: deploy-redirector
  namespace: aura
spec:
  prometheus:
    enabled: true
  env:
  - name: REDIRECT_URL
    value: "http://deploy.nais.io"
  image: navikt/deploy-redirector:0.6
  ingresses:
  - https://deploy-redirector.prod-sbs.nais.io
  port: 8080
  replicas:
    max: 1
    min: 1
