name: canary release
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  deploy:
    name: Deploy with NAIS deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        cat > vars.yml << EOF
---
image: docker.pkg.github.com/nais/testapp/testapp:latest
now: $(date +%s%N)
fqdn: nais-deploy-canary.dev-fss.nais.io
EOF
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: canary.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
