# vi: se ft=yaml:
---

name: Canary deployment
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  dev-fss:
    name: Deploy canary to dev-fss
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        echo "---" > vars.yml
        echo "image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7" >> vars.yml
        echo "now: $(date +%s%N)" >> vars.yml
        echo "fqdn: nais-deploy-canary.dev-fss.nais.io" >> vars.yml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: canary.yml
        VARS: vars.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
        PRINT_PAYLOAD: true

  prod-fss:
    name: Deploy canary to prod-fss
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        echo "---" > vars.yml
        echo "image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7" >> vars.yml
        echo "now: $(date +%s%N)" >> vars.yml
        echo "fqdn: nais-deploy-canary.prod-fss.nais.io" >> vars.yml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-fss
        RESOURCE: canary.yml
        VARS: vars.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
        PRINT_PAYLOAD: true

  dev-sbs:
    name: Deploy canary to dev-sbs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        echo "---" > vars.yml
        echo "image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7" >> vars.yml
        echo "now: $(date +%s%N)" >> vars.yml
        echo "fqdn: nais-deploy-canary.dev-sbs.nais.io" >> vars.yml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-sbs
        RESOURCE: canary.yml
        VARS: vars.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
        PRINT_PAYLOAD: true

  prod-sbs:
    name: Deploy canary to prod-sbs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        echo "---" > vars.yml
        echo "image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7" >> vars.yml
        echo "now: $(date +%s%N)" >> vars.yml
        echo "fqdn: nais-deploy-canary.prod-sbs.nais.io" >> vars.yml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-sbs
        RESOURCE: canary.yml
        VARS: vars.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
        PRINT_PAYLOAD: true

  dev-gcp:
    name: Deploy canary to dev-gcp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        echo "---" > vars.yml
        echo "image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7" >> vars.yml
        echo "now: $(date +%s%N)" >> vars.yml
        echo "fqdn: nais-deploy-canary.dev-gcp.nais.io" >> vars.yml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: canary.yml
        VARS: vars.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
        PRINT_PAYLOAD: true

  prod-gcp:
    name: Deploy canary to prod-gcp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate variables
      run: |
        echo "---" > vars.yml
        echo "image: docker.pkg.github.com/nais/testapp/testapp:2020-02-25-f61e7b7" >> vars.yml
        echo "now: $(date +%s%N)" >> vars.yml
        echo "fqdn: nais-deploy-canary.prod-gcp.nais.io" >> vars.yml
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: canary.yml
        VARS: vars.yml
        OWNER: navikt
        REPOSITORY: nais-deploy
        PRINT_PAYLOAD: true

