name: NAIS deploy release pipeline

on:
  push:
    paths-ignore:
    - '.github/workflows/codeql-analysis.yml'
    - '.github/workflows/job.yaml'
    - '.github/workflows/naisjob-without-schedule.yaml'
    - '.github/workflows/naisjob.yaml'
    - 'deploy/testdata/naisjob.yaml'
    - 'deploy/testdata/job.yaml'
    - 'deploy/testdata/naisjob-without-schedule.yaml'

env:
  image: ghcr.io/${{ github.repository }}/deploy
  hookd_image: ghcr.io/${{ github.repository }}/hookd
  deployd_image: ghcr.io/${{ github.repository }}/deployd
  canary_deployer_image: ghcr.io/${{ github.repository }}/canary-deployer
  dockerhub_image: navikt/deployment

jobs:

  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate version tags
      run: |
        echo "version=$(./version.sh)" >> $GITHUB_ENV
        echo "deploy_action_api_version=$(cat actions/deploy/version)" >> $GITHUB_ENV
    - name: Build Docker images
      run: |
        docker build --tag ${image}:${version} --tag ${image}:latest --tag ${image}:${deploy_action_api_version} .
        docker build --tag ${hookd_image}:${version} --tag ${hookd_image}:latest -f Dockerfile.hookd .
        docker build --tag ${deployd_image}:${version} --tag ${deployd_image}:latest -f Dockerfile.deployd .
        docker build --tag ${canary_deployer_image}:${version} --tag ${canary_deployer_image}:latest canary-deployer
    - name: Push versioned Docker image to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${image}:${version}
        docker push ${hookd_image}:${version}
        docker push ${deployd_image}:${version}
        docker push ${canary_deployer_image}:${version}
    - name: Push production Docker image to GitHub
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${image}:${deploy_action_api_version}
        docker push ${image}:latest
        docker push ${hookd_image}:latest
        docker push ${deployd_image}:latest
        docker push ${canary_deployer_image}:latest
    - name: Push production Docker image to Dockerhub
      if: github.ref == 'refs/heads/master'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
        docker tag ${image}:latest ${dockerhub_image}:${deploy_action_api_version}-grpc
        docker push ${dockerhub_image}:${deploy_action_api_version}-grpc

  release:
    name: Release versioned GitHub Action
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Force create tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git tag -f $(cat actions/deploy/version)
        git push -f --tags
    - name: Create deploy binaries
      run: |
        make deploy-release-linux
        make deploy-release-darwin
        make deploy-release-windows
    - name: Delete release if exists
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        latest=$(curl https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest)
        tag=$(echo $latest | jq .tag_name | xargs) # xargs strips quotes
        if grep -q "$tag" actions/deploy/version; then
          release_id=$(echo $latest | jq .id)
          curl -X DELETE https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@api.github.com/repos/${GITHUB_REPOSITORY}/releases/${release_id}
        fi
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        release=$(curl -X POST \
          -d '{"tag_name": "'"$(cat actions/deploy/version)"'"}' \
          -H "Content-Type: application/json" \
          https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@api.github.com/repos/${GITHUB_REPOSITORY}/releases)
        echo "release_id=$(echo $release | jq .id)" >> ${GITHUB_OUTPUT}
    - name: Upload Linux Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BINARY: deploy-linux
      run: |
        curl -X POST \
        -H 'Content-Type: application/x-executable' \
        --data-binary @${BINARY} \
        https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${{ steps.create_release.outputs.release_id }}/assets?name=${BINARY}
    - name: Upload Darwin Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BINARY: deploy-darwin
      run: |
        curl -X POST \
        -H 'Content-Type: application/x-executable' \
        --data-binary @${BINARY} \
        https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${{ steps.create_release.outputs.release_id }}/assets?name=${BINARY}
    - name: Upload Windows Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BINARY: deploy-windows
      run: |
        curl -X POST \
        -H 'Content-Type: application/x-executable' \
        --data-binary @${BINARY} \
        https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${{ steps.create_release.outputs.release_id }}/assets?name=${BINARY}

  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: deploy
    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
        app-id: ${{ secrets.NAIS_APP_ID }}
        repo: navikt/nais-yaml
    - name: Checkout nais-yaml
      uses: actions/checkout@v3
      with:
        repository: navikt/nais-yaml
        token: ${{ steps.get-token.outputs.token }}
        path: nais-yaml
    - name: Generate image environment variable
      run: |
        cd deploy
        version=$(./version.sh)
        echo "version=${version}" >> $GITHUB_ENV
        echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
    - name: Bump version in nais-yaml
      run: |
        cd nais-yaml
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        sed -E -i "s#hookdImage: .+#hookdImage: ${hookd_image}:${version}#" vars/global.yaml
        sed -E -i "s#deploydImage: .+#deploydImage: ${deployd_image}:${version}#" vars/global.yaml
        git add .
        git --no-pager diff --cached
        git commit --no-verify -a -m "Bump deployment orchestrator to version ${version}"
        git push

  rollout:
    name: Rollout with Fasit
    if: github.ref == 'refs/heads/master'
    needs: build
    permissions:
      id-token: write
    runs-on: fasit-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Generate version environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
      - uses: nais/fasit-deploy@main
        name: Rollout hookd
        with:
          json: '{"backend": {"image": {"tag": "${{ env.version }}"}}}'
          feature_name: hookd
      - uses: nais/fasit-deploy@main
        name: Rollout deployd
        with:
          json: '{"image": {"tag": "${{ env.version }}"}}'
          feature_name: deployd
